version: "3"

services:
  aws-sync:
    build:
      context: .
      args:
        - KEY=${KEY}
        - SECRET=${SECRET}
        - REGION=${REGION}
        - BUCKET=${BUCKET}
        - BUCKET_PATH=${BUCKET_PATH}
        - PARAMS=${PARAMS}
    env_file:
       - ./.env
    environment:
       - AWS_ACCESS_KEY_ID=${KEY}
       - AWS_SECRET_ACCESS_KEY=${SECRET}
       - AWS_DEFAULT_REGION=${REGION}
    volumes:
      - ${PATH_TO_SYNC}:/data:ro
